name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 UTC 自动运行
  workflow_dispatch:     # 可手动触发

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: wxingheng
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}